Task1_0507. 튜플 형태인 strings를 다양한 문자가 포함된 순서로 정렬하세요.

strings = ('a', 'ca', 'bar', 'aaaa', 'ababa')

In [5]:
strings = ('a', 'ca', 'bar', 'aaaa', 'ababa')
sorted_strings = sorted(strings, key=lambda x : len(set(x)), reverse=True)
print(sorted_strings)

['bar', 'ca', 'ababa', 'a', 'aaaa']

Task2_0507. eval 함수를 활용하여 a,b 변수와 연산자를 입력하면 사칙연산을 수행하는 코드를 작성하세요. (eval 사용하는 경우와 안하는 경우)

In [16]:
# eval을 사용하는 경우
expression = input("사칙연산을 수행할 표현식 \n(a)(연산자)(b) 를 입력 : ")
result = eval(expression)
print(f'\n{result:.2f}')

사칙연산을 수행할 표현식
(a)(연산자)(b) 를 입력 : 500/7

71.43

In [13]:
# eval을 사용하지 않는 경우
num1 = int(input("변수 a 입력 : "))
operator = input("계산할 연산자를 입력 : ")
num2 = int(input("변수 b 입력 : "))
if operator == '+':
  print(f'\n{num1} {operator} {num2} = {num1+num2}')
elif operator == '-':
  print(f'\n{num1} {operator} {num2} = {num1-num2}')
elif operator == '*':
  print(f'\n{num1} {operator} {num2} = {num1*num2}')
else :
  print(f'\n{num1} {operator} {num2} = {num1/num2:.2f}')

변수 a 입력 : 30
계산할 연산자를 입력 : /
변수 b 입력 : 7

30 / 7 = 4.29

Task3_0507. list1에 대해서 아래와 같이 출력하는 코드를 작성하세요.

인사평가 1번째 해당자는 김부장입니다. 회의실A로 오시기 바랍니다.\
인사평가 2번째 해당자는 이차장입니다. 회의실A로 오시기 바랍니다.\
인사평가 3번째 해당자는 김과장입니다. 회의실A로 오시기 바랍니다.\
인사평가 4번째 해당자는 이대리입니다. 회의실A로 오시기 바랍니다.\
인사평가 5번째 해당자는 오사원입니다. 회의실A로 오시기 바랍니다.\
인사평가 6번째 해당자는 김인턴입니다. 회의실A로 오시기 바랍니다.

In [18]:
list1 = ['김부장', '이차장', '김과장', '이대리', '오사원', '김인턴']
for idx, person in enumerate(list1) :
  print(f'인사평가 {idx+1}번째 해당자는 {person}입니다. 회의실A로 오시기 바랍니다.')

인사평가 1번째 해당자는 김부장입니다. 회의실A로 오시기 바랍니다.
인사평가 2번째 해당자는 이차장입니다. 회의실A로 오시기 바랍니다.
인사평가 3번째 해당자는 김과장입니다. 회의실A로 오시기 바랍니다.
인사평가 4번째 해당자는 이대리입니다. 회의실A로 오시기 바랍니다.
인사평가 5번째 해당자는 오사원입니다. 회의실A로 오시기 바랍니다.
인사평가 6번째 해당자는 김인턴입니다. 회의실A로 오시기 바랍니다.

Task4_0507. 주어진 문자열 리스트의 요소들을 대문자로 변환하세요.  
words = ["hello", "world", "python", "map"]

In [25]:
words = ["hello", "world", "python", "map"]

for i in range(len(words)) :
  words[i] = words[i].upper()
print(words)

['HELLO', 'WORLD', 'PYTHON', 'MAP']

Task5_0507. 주어진 리스트에서 'p'로 시작하는 단어만 필터링하세요.

words = ["python", "is", "powerful", "programming", "language", "pandas"]

In [28]:
words = ["python", "is", "powerful", "programming", "language", "pandas"]
filtered_words = filter(lambda x : x[0] == 'p', words)
print(list(filtered_words))

['python', 'powerful', 'programming', 'pandas']

Task6_0507. 내장함수를 이용해서 list = [0,1,2,3,4,5,6]에서 2를 삭제 후 출력하세요.(2가지 방법)

In [39]:
print("1. pop() 메서드 이용하기")
lst = list(range(7))
a = 0
print(f'원본 리스트 : {lst}')
a = lst.pop(2)  # 삭제할 값의 인덱스를 입력
print(f'삭제된 값 : {a}, 변경된 리스트 : {lst}\n')

print("2. remove() 메서드 이용하기")
lst = list(range(7))
print(f'원본 리스트 : {lst}')
rm = int(input("삭제할 값을 입력 : "))
if rm in lst :
  lst.remove(rm)  # 인덱스 대신 삭제할 값을 직접 입력
  print(f'변경된 리스트 : {lst}')
else :
  print("원본 리스트 안에 있는 값을 입력!")

1. pop() 메서드 이용하기
원본 리스트 : [0, 1, 2, 3, 4, 5, 6]
삭제된 값 : 2, 변경된 리스트 : [0, 1, 3, 4, 5, 6]

2. remove() 메서드 이용하기
원본 리스트 : [0, 1, 2, 3, 4, 5, 6]
삭제할 값을 입력 : 2
변경된 리스트 : [0, 1, 3, 4, 5, 6]

Task7_0507. 내장함수를 이용하여 동일한 개수로 이루어진 자료형을 화살표 좌측에서 우측으로 변환하세요.

[1,2,3],[4,5,6] -> [(1,4),(2,5),(3,6)]\
[1,2,3],[4,5,6] [7,8,9] -> [(1,4,7),(2,5,8),(3,6,9)]\
('abc','def') -> [('a','d'),('b','e'),('c','f')]

In [50]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
lst3 = [7, 8, 9]
tp1 = ('abc', 'def')
print(f'{lst1}, {lst2}\t\t -> \t{list(zip(lst1,lst2))}')
print(f'{lst1}, {lst2}, {lst3}\t -> \t{list(zip(lst1,lst2,lst3))}')
print(f'{tp1}\t\t\t -> \t{list(zip(tp1[0], tp1[1]))}')

[1, 2, 3], [4, 5, 6]		 -> 	[(1, 4), (2, 5), (3, 6)]
[1, 2, 3], [4, 5, 6], [7, 8, 9]	 -> 	[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
('abc', 'def')			 -> 	[('a', 'd'), ('b', 'e'), ('c', 'f')]

Task8_0507. url에서 호스트 도메인(news.naver.com)을 추출하여 출력하세요.

url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'

In [56]:
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'
temp = url.split('/')
domain = temp[2]
print(f'호스트 도메인은 http://{domain} 입니다.')

호스트 도메인은 http://news.naver.com 입니다.